databases:
  - name: nina-db
    plan: free
    databaseName: nina_db
    user: nina

services:
  - type: web
    name: nina-site
    plan: free
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn nina_project.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nina-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.9"
