# Generated by Django 6.1 on 2026-08-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texte de la citation')),
                ('author', models.CharField(default='Nina', max_length=100, verbose_name='Auteur')),
                ('image', models.ImageField(upload_to='citations/', verbose_name='Illustration')),
                ('category', models.CharField(choices=[('amour', 'Amour'), ('vie', 'Vie'), ('inspiration', 'Inspiration'), ('sagesse', 'Sagesse'), ('reve', 'Rêve'), ('autre', 'Autre')], default='inspiration', max_length=20, verbose_name='Catégorie')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publiée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
                'ordering': ['-created_at'],
            },
        ),
    ]
